---
global:
  scrape_interval: 15s  # Set scrape interval to 15s. Default is 1 minute
  evaluation_interval: 15s  # Evaluate rules every 15s. Default is 1 minute

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
        # - alertmanager:9093

# Load rules once and periodically evaluate them according to the
# global 'evaluation_interval'.
rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped
  # from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'dns-discovery-api-gateway'
    dns_sd_configs:
      - names:
          - 'give-${ENVIRONMENT_NAME}.apps.internal'
        type: 'A'
        port: 8100

  - job_name: 'dns-discovery-usps'
    dns_sd_configs:
      - names:
          - 'identity-give-usps-${ENVIRONMENT_NAME}.apps.internal'
        type: 'A'
        port: 8080

  - job_name: 'dns-discovery-idemia'
    dns_sd_configs:
      - names:
          - 'identity-give-idemia-${ENVIRONMENT_NAME}.apps.internal'
        type: 'A'
        port: 8080

  - job_name: 'dns-discovery-cf-metrics'
    dns_sd_configs:
      - names:
          - 'identity-give-cf-metrics-${ENVIRONMENT_NAME}.apps.internal'
        type: 'A'
        port: 8080
