---
# This workflow will run unit tests and deploy the application to
# a target environment

name: Deploy

on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths-ignore:
      - '**.md'  # All markdown files in the repository
  release:
    types: [released]

jobs:
  check-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate config files
        run: |
          envsubst < prometheus/prometheus-config.yml > prometheus/prometheus.yml
          envsubst < alertmanager/alert-config.yml > alertmanager/alertmanager.yml
        env:
          # Use 'fake' environment variables since we're just checking syntax
          ENVIRONMENT_NAME: dev
          SLACK_URL: https://slack.com

      - name: Validate Prometheus Config
        run: |
          ./install_prometheus.sh
          ./promtool check config prometheus.yml
        working-directory: ./prometheus

      - name: Validate Alertmanager Config
        run: |
          ./install_alertmanager.sh
          ./amtool check-config alertmanager.yml
        working-directory: ./alertmanager

  deploy:
    if: github.repository_owner == '18F'
    needs: check-config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: 18F/identity-idva-cf-setup@v2
        id: cf-setup
        with:
          cf-username: ${{ secrets.CF_USERNAME }}
          cf-password: ${{ secrets.CF_PASSWORD }}
          cf-org: ${{ secrets.CF_ORG }}

      - name: Generate config files
        run: |
          envsubst < prometheus/prometheus-config.yml > prometheus/prometheus.yml
          envsubst < alertmanager/alert-config.yml > alertmanager/alertmanager.yml
        env:
          ENVIRONMENT_NAME: ${{ steps.cf-setup.outputs.target-environment }}
          SLACK_URL: ${{ secrets.SLACK_URL }}

      # Deploy the main 'monitoring' prometheus application
      - name: Deploy application
        run: cf push --vars-file vars.yaml
          --var ENVIRONMENT_NAME=${{ steps.cf-setup.outputs.target-environment }}
          --strategy rolling
        working-directory: ./prometheus

      # Deploy the prometheus alertmanager
      - name: Deploy alerts
        run: cf push
          --var ENVIRONMENT_NAME=${{ steps.cf-setup.outputs.target-environment }}
          --var SLACK_URL=${{ secrets.SLACK_URL }}
          --memory 64MB
          --instances 2
        working-directory: ./alertmanager

      - name: Apply CF Network Policies
        run: |
          cf add-network-policy alerts alerts --protocol tcp --port 9094
          cf add-network-policy alerts alerts --protocol udp --port 9094
          cf add-network-policy monitoring alerts
          cf add-network-policy monitoring cf-metrics
          cf add-network-policy monitoring api-gateway --port 8100 --protocol tcp
